version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: photo-service-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: photo-service
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  photo-service:
    build: .
    container_name: photo-service-backend
    command:
      - ./main
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ENV=local
      - CONFIG_PATH=./configs/config.yaml
      - DATABASE_PASSWORD=postgres
      - DB_PASSWORD=postgres
      - GRPC_PORT=50053
    ports:
      - "50053:50053"
    env_file:
      - ./.env

volumes:
  postgres_data:
