env: 'local'
database:
  dialect: 'postgres'
  host: 'postgres'
  port: '5432'
  name: 'auth-service'
  username: 'postgres'
  migration: true
grpc:
  port: 50051
  timeout: 10s
redis:
  host: 'redis'
  port: 6379
token:
  accessTokenTTL: 15m
  refreshTokenTTL: 7d