version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-service
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: .
    container_name: backend
    command:
      - ./main
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - ENV=local
      - CONFIG_PATH=./configs/config.yaml
      - JWT_KEY=#@!FEWMEKF
      - DATABASE_DIALECT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=auth-service
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DB_PASSWORD=postgres
      - GRPC_PORT=50051
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TOKEN_ACCESS_TTL=15m
      - TOKEN_REFRESH_TTL=7d
    ports:
      - "50051:50051"
    env_file:
      - ./.env

volumes:
  postgres_data:
